### ISSUE TITLE
Account deletions fails

### ISSUE THREAD

**Issue by rubenelshof** [flurrybox/enhanced-privacy#2]
I have setup Account Deletion and Anonymization using most of the default settings.
Account deletion time is set at 60 minutes.
Account deletion type is set at "Delete if no orders made, anonymize otherwise"

I created at test account and placed a test order.
I then tried to delete the account.
The process to delete in the customer account was fine but the account is not anonymized as it should have been. Both in the Magento backend aswell as in the database the customer name etc. are still visible.

The account has also not been deleted despite the 60 minutes set.

I cant find anything in the logs.

Any clues

**Comment by flurrybox** [comment]
Thanks for reporting the issue.
Can you update extension to latest version and make sure CRON is running correctly?

**Comment by rubenelshof** [comment]
I can confirm that it now deletes the account. It might have been an issue with CRON.
